name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
          proj-path: ConsoleWizard/ConsoleWizard.csproj
    - name: Package
      run: dotnet pack ConsoleWizard.sln -c Release -p:PackageVersion=${{ steps.get-version.outputs.package-version }} --no-build --no-restore
    - name: Publish
      run: dotnet nuget push **\**.nupkg --skip-duplicate -s 'https://api.nuget.orgv3/index.json' -ApiKey ${{ secrets.NUGET_API_KEY }} 
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get-version.outputs.package-version }}
        release_name: Release ${{ steps.get-version.outputs.package-version }} 
